### ISSUE TITLE
Auto-refresh after whitelisting 

### ISSUE THREAD

**Issue by christasich** [badsgahhl/pihole-chrome-extension#17]
**Is your feature request related to a problem? Please describe.**

After adding a URL to the white list via the extension, I need to manually refresh the page. This is cumbersome when links use multiple intermediary links to get to the final URL (e.g. Slickdeals.net).

**Describe the solution you'd like**

After adding a URL to the whitelist via the chrome extension, it would be nice for the page to automatically reload.

**Describe alternatives you've considered**

Manually refreshing the page.

**Additional context**

Thanks for the extension! It's extremely useful!

**Comment by badsgahhl** [comment]
@christasich Do you really mean "after whitelisting"? I think you mean the on/off switch?

Lets say you are on one of those redirecting domains where you go to 2-4 domains at once, and all of them are blocked.
You would then whitelist the first domain -> extension reloads the page -> you get to the second domain that is blocked.

This seems a little bit weired to me.
I would understand the following as more usefull, because you typically don't want to whitelist all of these redirecting domains.

My Solution:

You are on a blocked domain -> Press the pihole offline switch -> extension reloades and you get pass all domains as fast as possible.

Is this maybe the thing you want?

**Comment by christasich** [comment]
@badsgahhl That would also be useful. I did mean whitelisting though. My personal issue comes from browsing www.slickdeals.net. I use this site to monitor deals. The links they use are often passed through multiple hops (slickdeals -> site 1 - > site 2 -> site 3 -> final url). I've looked into these domains and I feel comfortable whitelisting them all. I think the auto-refresh option would be useful for both toggling the switch on/off and when whitelisting.

![WAsGkagESH](https://user-images.githubusercontent.com/5304026/85147188-1afb7a80-b214-11ea-95d2-76e3eb6cd388.gif)

**Comment by badsgahhl** [comment]
Ah ok, cool idea. 

I will play around with it a bit and see how it harmonizes well together. 

Maybe it will become an option that you have to activate in the settings, and you can deactivate it if you don't want to have it.

**Comment by christasich** [comment]
Yeah. I think opting into the setting is a reasonable way of handling it. It seems safer to have it off by default. Thanks for being responsive to the idea!

**Comment by badsgahhl** [comment]
There will be now the option to "Reload current tab after Whitelisting" and "Reload current tab after Disabling".

Blacklisting makes problems with caching and makes not so much sense.
Enabling and reloading is the same.
