### ISSUE TITLE
Firefox - Err on disable

### ISSUE THREAD

**Issue by chrischerman** [badsgahhl/pihole-chrome-extension#5]
On Firefox, when I click the button to disable, the icon changes from "On" to "ERR".  I've configured a number of ways from the server name to the IP address of the server.  I've made sure I have /admin after the server address.  Still always "ERR".

**Comment by badsgahhl** [comment]
Hello,

so i see that the extension shows the correct state of your pihole, because you see "On". Is this correct?
Getting an error switching the pihole off (from on) indicates that the API Call failed. This indicates that there is probably something wrong with your API Key. Please check that the api key is complete.

**Comment by chrischerman** [comment]
Well, this is embarrassing.  There was a space at the end of my API key from when I copy/pasted it from PiHole.  Some good feedback might be to have the software trim or ignore spaces from the input.  Working now.

**Comment by badsgahhl** [comment]
Good Point, i will check if there is a possibility to validate the api key and trim spaces out. 
Thanks for the feedback!
